### PR TITLE
Gm scripts

### PR DESCRIPTION
**Pull request by gmarkay**
## DESCRIPTION
Changed scripts for test and db:build in package.js

## STEPS TO TEST
1. In terminal type npm run db:build - should build database
2. npm test - should run test file

## REFERENCE
Does it reference a ticket?

### CODE REVIEW

**Comment by kylesaldana5** [comment]
Looks good 💯

**Comment by EduardoDuQuesne** [comment]
Workin real good 👍

**Comment by Craig-Orcutt** [comment]
well played good sir

**Comment by ben-marcantel** [comment]
nice

**Pull request merged**
