### PR TITLE
get products test ready?

### PR DESCRIPTION
**Pull request by ben-marcantel**
## DESCRIPTION
What did you do? 
set up testing and model functions for  get all, get one, adding new  products function, except for update
Why did you do it?
fullfills requirements

## STEPS TO TEST
1. run npm test in terminal, should return 11 passing tests

## REFERENCE
Does it reference a ticket?
#4 and #8

### CODE REVIEW

**Comment by EduardoDuQuesne** [comment]
Tests are passing 👍

**Comment by kylesaldana5** [comment]
Looks good on my end 🥇

**Comment by gmarkay** [comment]
Passing

**Comment by Craig-Orcutt** [comment]
Pulled down the updated branch. everything appears correct. Nice patch!

**Pull request merged**
